// Generated by gencpp from file std_stamped_msgs/EmptyStamped.msg
// DO NOT EDIT!


#ifndef STD_STAMPED_MSGS_MESSAGE_EMPTYSTAMPED_H
#define STD_STAMPED_MSGS_MESSAGE_EMPTYSTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace std_stamped_msgs
{
template <class ContainerAllocator>
struct EmptyStamped_
{
  typedef EmptyStamped_<ContainerAllocator> Type;

  EmptyStamped_()
    : stamp()  {
    }
  EmptyStamped_(const ContainerAllocator& _alloc)
    : stamp()  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;





  typedef boost::shared_ptr< ::std_stamped_msgs::EmptyStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::std_stamped_msgs::EmptyStamped_<ContainerAllocator> const> ConstPtr;

}; // struct EmptyStamped_

typedef ::std_stamped_msgs::EmptyStamped_<std::allocator<void> > EmptyStamped;

typedef boost::shared_ptr< ::std_stamped_msgs::EmptyStamped > EmptyStampedPtr;
typedef boost::shared_ptr< ::std_stamped_msgs::EmptyStamped const> EmptyStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::std_stamped_msgs::EmptyStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::std_stamped_msgs::EmptyStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::std_stamped_msgs::EmptyStamped_<ContainerAllocator1> & lhs, const ::std_stamped_msgs::EmptyStamped_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::std_stamped_msgs::EmptyStamped_<ContainerAllocator1> & lhs, const ::std_stamped_msgs::EmptyStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace std_stamped_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::std_stamped_msgs::EmptyStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::std_stamped_msgs::EmptyStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::std_stamped_msgs::EmptyStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::std_stamped_msgs::EmptyStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::std_stamped_msgs::EmptyStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::std_stamped_msgs::EmptyStamped_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::std_stamped_msgs::EmptyStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "84d365d08d5fc49dde870daba1c7992c";
  }

  static const char* value(const ::std_stamped_msgs::EmptyStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x84d365d08d5fc49dULL;
  static const uint64_t static_value2 = 0xde870daba1c7992cULL;
};

template<class ContainerAllocator>
struct DataType< ::std_stamped_msgs::EmptyStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_stamped_msgs/EmptyStamped";
  }

  static const char* value(const ::std_stamped_msgs::EmptyStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::std_stamped_msgs::EmptyStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
;
  }

  static const char* value(const ::std_stamped_msgs::EmptyStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::std_stamped_msgs::EmptyStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EmptyStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::std_stamped_msgs::EmptyStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::std_stamped_msgs::EmptyStamped_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STD_STAMPED_MSGS_MESSAGE_EMPTYSTAMPED_H
