// Generated by gencpp from file std_stamped_msgs/Int16MultiArrayStamped.msg
// DO NOT EDIT!


#ifndef STD_STAMPED_MSGS_MESSAGE_INT16MULTIARRAYSTAMPED_H
#define STD_STAMPED_MSGS_MESSAGE_INT16MULTIARRAYSTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_stamped_msgs/MultiArrayLayout.h>

namespace std_stamped_msgs
{
template <class ContainerAllocator>
struct Int16MultiArrayStamped_
{
  typedef Int16MultiArrayStamped_<ContainerAllocator> Type;

  Int16MultiArrayStamped_()
    : stamp()
    , layout()
    , data()  {
    }
  Int16MultiArrayStamped_(const ContainerAllocator& _alloc)
    : stamp()
    , layout(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef  ::std_stamped_msgs::MultiArrayLayout_<ContainerAllocator>  _layout_type;
  _layout_type layout;

   typedef std::vector<int16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int16_t>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::std_stamped_msgs::Int16MultiArrayStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::std_stamped_msgs::Int16MultiArrayStamped_<ContainerAllocator> const> ConstPtr;

}; // struct Int16MultiArrayStamped_

typedef ::std_stamped_msgs::Int16MultiArrayStamped_<std::allocator<void> > Int16MultiArrayStamped;

typedef boost::shared_ptr< ::std_stamped_msgs::Int16MultiArrayStamped > Int16MultiArrayStampedPtr;
typedef boost::shared_ptr< ::std_stamped_msgs::Int16MultiArrayStamped const> Int16MultiArrayStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::std_stamped_msgs::Int16MultiArrayStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::std_stamped_msgs::Int16MultiArrayStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::std_stamped_msgs::Int16MultiArrayStamped_<ContainerAllocator1> & lhs, const ::std_stamped_msgs::Int16MultiArrayStamped_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.layout == rhs.layout &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::std_stamped_msgs::Int16MultiArrayStamped_<ContainerAllocator1> & lhs, const ::std_stamped_msgs::Int16MultiArrayStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace std_stamped_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::std_stamped_msgs::Int16MultiArrayStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::std_stamped_msgs::Int16MultiArrayStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::std_stamped_msgs::Int16MultiArrayStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::std_stamped_msgs::Int16MultiArrayStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::std_stamped_msgs::Int16MultiArrayStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::std_stamped_msgs::Int16MultiArrayStamped_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::std_stamped_msgs::Int16MultiArrayStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6d46631431076de17d677839e34355dd";
  }

  static const char* value(const ::std_stamped_msgs::Int16MultiArrayStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6d46631431076de1ULL;
  static const uint64_t static_value2 = 0x7d677839e34355ddULL;
};

template<class ContainerAllocator>
struct DataType< ::std_stamped_msgs::Int16MultiArrayStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_stamped_msgs/Int16MultiArrayStamped";
  }

  static const char* value(const ::std_stamped_msgs::Int16MultiArrayStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::std_stamped_msgs::Int16MultiArrayStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"time stamp\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"int16[]           data          # array of data\n"
"================================================================================\n"
"MSG: std_stamped_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"#\n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_stamped_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::std_stamped_msgs::Int16MultiArrayStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::std_stamped_msgs::Int16MultiArrayStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.layout);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Int16MultiArrayStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::std_stamped_msgs::Int16MultiArrayStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::std_stamped_msgs::Int16MultiArrayStamped_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "layout: ";
    s << std::endl;
    Printer< ::std_stamped_msgs::MultiArrayLayout_<ContainerAllocator> >::stream(s, indent + "  ", v.layout);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // STD_STAMPED_MSGS_MESSAGE_INT16MULTIARRAYSTAMPED_H
