// Generated by gencpp from file std_stamped_msgs/StringServiceRequest.msg
// DO NOT EDIT!


#ifndef STD_STAMPED_MSGS_MESSAGE_STRINGSERVICEREQUEST_H
#define STD_STAMPED_MSGS_MESSAGE_STRINGSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace std_stamped_msgs
{
template <class ContainerAllocator>
struct StringServiceRequest_
{
  typedef StringServiceRequest_<ContainerAllocator> Type;

  StringServiceRequest_()
    : request()  {
    }
  StringServiceRequest_(const ContainerAllocator& _alloc)
    : request(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _request_type;
  _request_type request;





  typedef boost::shared_ptr< ::std_stamped_msgs::StringServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::std_stamped_msgs::StringServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StringServiceRequest_

typedef ::std_stamped_msgs::StringServiceRequest_<std::allocator<void> > StringServiceRequest;

typedef boost::shared_ptr< ::std_stamped_msgs::StringServiceRequest > StringServiceRequestPtr;
typedef boost::shared_ptr< ::std_stamped_msgs::StringServiceRequest const> StringServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::std_stamped_msgs::StringServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::std_stamped_msgs::StringServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::std_stamped_msgs::StringServiceRequest_<ContainerAllocator1> & lhs, const ::std_stamped_msgs::StringServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.request == rhs.request;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::std_stamped_msgs::StringServiceRequest_<ContainerAllocator1> & lhs, const ::std_stamped_msgs::StringServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace std_stamped_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::std_stamped_msgs::StringServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::std_stamped_msgs::StringServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::std_stamped_msgs::StringServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::std_stamped_msgs::StringServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::std_stamped_msgs::StringServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::std_stamped_msgs::StringServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::std_stamped_msgs::StringServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b13f31f7a0a36901919f7ec0d9f40d4";
  }

  static const char* value(const ::std_stamped_msgs::StringServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b13f31f7a0a3690ULL;
  static const uint64_t static_value2 = 0x1919f7ec0d9f40d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::std_stamped_msgs::StringServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_stamped_msgs/StringServiceRequest";
  }

  static const char* value(const ::std_stamped_msgs::StringServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::std_stamped_msgs::StringServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string request\n"
;
  }

  static const char* value(const ::std_stamped_msgs::StringServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::std_stamped_msgs::StringServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StringServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::std_stamped_msgs::StringServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::std_stamped_msgs::StringServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "request: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.request);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STD_STAMPED_MSGS_MESSAGE_STRINGSERVICEREQUEST_H
