// Generated by gencpp from file std_stamped_msgs/UInt64Stamped.msg
// DO NOT EDIT!


#ifndef STD_STAMPED_MSGS_MESSAGE_UINT64STAMPED_H
#define STD_STAMPED_MSGS_MESSAGE_UINT64STAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace std_stamped_msgs
{
template <class ContainerAllocator>
struct UInt64Stamped_
{
  typedef UInt64Stamped_<ContainerAllocator> Type;

  UInt64Stamped_()
    : stamp()
    , data(0)  {
    }
  UInt64Stamped_(const ContainerAllocator& _alloc)
    : stamp()
    , data(0)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef uint64_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::std_stamped_msgs::UInt64Stamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::std_stamped_msgs::UInt64Stamped_<ContainerAllocator> const> ConstPtr;

}; // struct UInt64Stamped_

typedef ::std_stamped_msgs::UInt64Stamped_<std::allocator<void> > UInt64Stamped;

typedef boost::shared_ptr< ::std_stamped_msgs::UInt64Stamped > UInt64StampedPtr;
typedef boost::shared_ptr< ::std_stamped_msgs::UInt64Stamped const> UInt64StampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::std_stamped_msgs::UInt64Stamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::std_stamped_msgs::UInt64Stamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::std_stamped_msgs::UInt64Stamped_<ContainerAllocator1> & lhs, const ::std_stamped_msgs::UInt64Stamped_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::std_stamped_msgs::UInt64Stamped_<ContainerAllocator1> & lhs, const ::std_stamped_msgs::UInt64Stamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace std_stamped_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::std_stamped_msgs::UInt64Stamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::std_stamped_msgs::UInt64Stamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::std_stamped_msgs::UInt64Stamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::std_stamped_msgs::UInt64Stamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::std_stamped_msgs::UInt64Stamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::std_stamped_msgs::UInt64Stamped_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::std_stamped_msgs::UInt64Stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4ed310d53deb7fbf2f491839395b05c0";
  }

  static const char* value(const ::std_stamped_msgs::UInt64Stamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4ed310d53deb7fbfULL;
  static const uint64_t static_value2 = 0x2f491839395b05c0ULL;
};

template<class ContainerAllocator>
struct DataType< ::std_stamped_msgs::UInt64Stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_stamped_msgs/UInt64Stamped";
  }

  static const char* value(const ::std_stamped_msgs::UInt64Stamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::std_stamped_msgs::UInt64Stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"uint64 data\n"
;
  }

  static const char* value(const ::std_stamped_msgs::UInt64Stamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::std_stamped_msgs::UInt64Stamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UInt64Stamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::std_stamped_msgs::UInt64Stamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::std_stamped_msgs::UInt64Stamped_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "data: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STD_STAMPED_MSGS_MESSAGE_UINT64STAMPED_H
