; Auto-generated. Do not edit!


(cl:in-package std_stamped_msgs-msg)


;//! \htmlinclude StringResult.msg.html

(cl:defclass <StringResult> (roslisp-msg-protocol:ros-message)
  ((status
    :reader status
    :initarg :status
    :type cl:fixnum
    :initform 0))
)

(cl:defclass StringResult (<StringResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StringResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StringResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name std_stamped_msgs-msg:<StringResult> is deprecated: use std_stamped_msgs-msg:StringResult instead.")))

(cl:ensure-generic-function 'status-val :lambda-list '(m))
(cl:defmethod status-val ((m <StringResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader std_stamped_msgs-msg:status-val is deprecated.  Use std_stamped_msgs-msg:status instead.")
  (status m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StringResult>) ostream)
  "Serializes a message object of type '<StringResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'status)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StringResult>) istream)
  "Deserializes a message object of type '<StringResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'status)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StringResult>)))
  "Returns string type for a message object of type '<StringResult>"
  "std_stamped_msgs/StringResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StringResult)))
  "Returns string type for a message object of type 'StringResult"
  "std_stamped_msgs/StringResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StringResult>)))
  "Returns md5sum for a message object of type '<StringResult>"
  "284aa12dd9e9e760802ac9f38036ea5e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StringResult)))
  "Returns md5sum for a message object of type 'StringResult"
  "284aa12dd9e9e760802ac9f38036ea5e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StringResult>)))
  "Returns full string definition for message of type '<StringResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result definition~%uint8 status~%# value follow actionlib_msgs/GoalStatus.status:~%# uint8 PENDING=0~%# uint8 ACTIVE=1~%# uint8 PREEMPTED=2~%# uint8 SUCCEEDED=3~%# uint8 ABORTED=4~%# uint8 REJECTED=5~%# uint8 PREEMPTING=6~%# uint8 RECALLING=7~%# uint8 RECALLED=8~%# uint8 LOST=9~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StringResult)))
  "Returns full string definition for message of type 'StringResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result definition~%uint8 status~%# value follow actionlib_msgs/GoalStatus.status:~%# uint8 PENDING=0~%# uint8 ACTIVE=1~%# uint8 PREEMPTED=2~%# uint8 SUCCEEDED=3~%# uint8 ABORTED=4~%# uint8 REJECTED=5~%# uint8 PREEMPTING=6~%# uint8 RECALLING=7~%# uint8 RECALLED=8~%# uint8 LOST=9~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StringResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StringResult>))
  "Converts a ROS message object to a list"
  (cl:list 'StringResult
    (cl:cons ':status (status msg))
))
