set(_CATKIN_CURRENT_PACKAGE "safety_msgs")
set(safety_msgs_VERSION "0.0.0")
set(safety_msgs_MAINTAINER "huy <huy@todo.todo>")
set(safety_msgs_PACKAGE_FORMAT "2")
set(safety_msgs_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "message_generation")
set(safety_msgs_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs")
set(safety_msgs_BUILDTOOL_DEPENDS "catkin")
set(safety_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(safety_msgs_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "message_generation" "message_runtime")
set(safety_msgs_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "message_generation" "message_runtime")
set(safety_msgs_TEST_DEPENDS )
set(safety_msgs_DOC_DEPENDS )
set(safety_msgs_URL_WEBSITE "")
set(safety_msgs_URL_BUGTRACKER "")
set(safety_msgs_URL_REPOSITORY "")
set(safety_msgs_DEPRECATED "")