set(_CATKIN_CURRENT_PACKAGE "scan_safety")
set(scan_safety_VERSION "0.0.0")
set(scan_safety_MAINTAINER "huy <huy@todo.todo>")
set(scan_safety_PACKAGE_FORMAT "2")
set(scan_safety_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "dynamic_reconfigure" "message_generation")
set(scan_safety_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "dynamic_reconfigure")
set(scan_safety_BUILDTOOL_DEPENDS "catkin")
set(scan_safety_BUILDTOOL_EXPORT_DEPENDS )
set(scan_safety_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime" "dynamic_reconfigure")
set(scan_safety_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime" "dynamic_reconfigure")
set(scan_safety_TEST_DEPENDS )
set(scan_safety_DOC_DEPENDS )
set(scan_safety_URL_WEBSITE "")
set(scan_safety_URL_BUGTRACKER "")
set(scan_safety_URL_REPOSITORY "")
set(scan_safety_DEPRECATED "")