set(_CATKIN_CURRENT_PACKAGE "rviz_control_panel")
set(rviz_control_panel_VERSION "0.0.0")
set(rviz_control_panel_MAINTAINER "thinh <thinh@todo.todo>")
set(rviz_control_panel_PACKAGE_FORMAT "2")
set(rviz_control_panel_BUILD_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "rviz")
set(rviz_control_panel_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(rviz_control_panel_BUILDTOOL_DEPENDS "catkin")
set(rviz_control_panel_BUILDTOOL_EXPORT_DEPENDS )
set(rviz_control_panel_EXEC_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "rviz")
set(rviz_control_panel_RUN_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "rviz")
set(rviz_control_panel_TEST_DEPENDS )
set(rviz_control_panel_DOC_DEPENDS )
set(rviz_control_panel_URL_WEBSITE "")
set(rviz_control_panel_URL_BUGTRACKER "")
set(rviz_control_panel_URL_REPOSITORY "")
set(rviz_control_panel_DEPRECATED "")