(cl:defpackage scan_safety-srv
  (:use )
  (:export
   "SAFETYCONTROL"
   "<SAFETYCONTROL-REQUEST>"
   "SAFETYCONTROL-REQUEST"
   "<SAFETYCONTROL-RESPONSE>"
   "SAFETYCONTROL-RESPONSE"
   "SAFETYENABLE"
   "<SAFETYENABLE-REQUEST>"
   "SAFETYENABLE-REQUEST"
   "<SAFETYENABLE-RESPONSE>"
   "SAFETYENABLE-RESPONSE"
  ))

