// Generated by gencpp from file restricted_layer/DataArray.msg
// DO NOT EDIT!


#ifndef RESTRICTED_LAYER_MESSAGE_DATAARRAY_H
#define RESTRICTED_LAYER_MESSAGE_DATAARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <restricted_layer/Data.h>

namespace restricted_layer
{
template <class ContainerAllocator>
struct DataArray_
{
  typedef DataArray_<ContainerAllocator> Type;

  DataArray_()
    : data()  {
    }
  DataArray_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::restricted_layer::Data_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::restricted_layer::Data_<ContainerAllocator> >> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::restricted_layer::DataArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::restricted_layer::DataArray_<ContainerAllocator> const> ConstPtr;

}; // struct DataArray_

typedef ::restricted_layer::DataArray_<std::allocator<void> > DataArray;

typedef boost::shared_ptr< ::restricted_layer::DataArray > DataArrayPtr;
typedef boost::shared_ptr< ::restricted_layer::DataArray const> DataArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::restricted_layer::DataArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::restricted_layer::DataArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::restricted_layer::DataArray_<ContainerAllocator1> & lhs, const ::restricted_layer::DataArray_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::restricted_layer::DataArray_<ContainerAllocator1> & lhs, const ::restricted_layer::DataArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace restricted_layer

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::restricted_layer::DataArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::restricted_layer::DataArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::restricted_layer::DataArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::restricted_layer::DataArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::restricted_layer::DataArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::restricted_layer::DataArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::restricted_layer::DataArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aee3eb144bbf6cd2eb2d2f628b793624";
  }

  static const char* value(const ::restricted_layer::DataArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaee3eb144bbf6cd2ULL;
  static const uint64_t static_value2 = 0xeb2d2f628b793624ULL;
};

template<class ContainerAllocator>
struct DataType< ::restricted_layer::DataArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "restricted_layer/DataArray";
  }

  static const char* value(const ::restricted_layer::DataArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::restricted_layer::DataArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Data[] data\n"
"\n"
"================================================================================\n"
"MSG: restricted_layer/Data\n"
"float64 x\n"
"float64 y\n"
;
  }

  static const char* value(const ::restricted_layer::DataArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::restricted_layer::DataArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DataArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::restricted_layer::DataArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::restricted_layer::DataArray_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::restricted_layer::Data_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RESTRICTED_LAYER_MESSAGE_DATAARRAY_H
