// Generated by gencpp from file restricted_layer/Data.msg
// DO NOT EDIT!


#ifndef RESTRICTED_LAYER_MESSAGE_DATA_H
#define RESTRICTED_LAYER_MESSAGE_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace restricted_layer
{
template <class ContainerAllocator>
struct Data_
{
  typedef Data_<ContainerAllocator> Type;

  Data_()
    : x(0.0)
    , y(0.0)  {
    }
  Data_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::restricted_layer::Data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::restricted_layer::Data_<ContainerAllocator> const> ConstPtr;

}; // struct Data_

typedef ::restricted_layer::Data_<std::allocator<void> > Data;

typedef boost::shared_ptr< ::restricted_layer::Data > DataPtr;
typedef boost::shared_ptr< ::restricted_layer::Data const> DataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::restricted_layer::Data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::restricted_layer::Data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::restricted_layer::Data_<ContainerAllocator1> & lhs, const ::restricted_layer::Data_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::restricted_layer::Data_<ContainerAllocator1> & lhs, const ::restricted_layer::Data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace restricted_layer

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::restricted_layer::Data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::restricted_layer::Data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::restricted_layer::Data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::restricted_layer::Data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::restricted_layer::Data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::restricted_layer::Data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::restricted_layer::Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "209f516d3eb691f0663e25cb750d67c1";
  }

  static const char* value(const ::restricted_layer::Data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x209f516d3eb691f0ULL;
  static const uint64_t static_value2 = 0x663e25cb750d67c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::restricted_layer::Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "restricted_layer/Data";
  }

  static const char* value(const ::restricted_layer::Data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::restricted_layer::Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
;
  }

  static const char* value(const ::restricted_layer::Data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::restricted_layer::Data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::restricted_layer::Data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::restricted_layer::Data_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RESTRICTED_LAYER_MESSAGE_DATA_H
