#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH='/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/std_stamped_msgs:/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/scan_safety:/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/safety_msgs:/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/rviz_navigation_plugin:/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/rviz_custom:/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/rviz_control_panel:/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/rf2o_laser_odometry:/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/restricted_layer:/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/nexus_4wd_mecanum_gazebo:/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/nexus_4wd_mecanum_description:/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/follow_waypoints:/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/cartographer_ros:/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/cartographer_ros_msgs:/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/als_ros:/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/cartographer_rviz:/opt/ros/noetic:/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/cartographer'
export LD_LIBRARY_PATH='/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/scan_safety/lib:/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/safety_msgs/lib:/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/rviz_navigation_plugin/lib:/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/rviz_custom/lib:/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/rviz_control_panel/lib:/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/rf2o_laser_odometry/lib:/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/restricted_layer/lib:/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/nexus_4wd_mecanum_gazebo/lib:/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/nexus_4wd_mecanum_description/lib:/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/follow_waypoints/lib:/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/cartographer_ros/lib:/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/cartographer_ros_msgs/lib:/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/als_ros/lib:/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/cartographer_rviz/lib:/opt/ros/noetic/lib:/opt/ros/noetic/lib/x86_64-linux-gnu:/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/cartographer/lib:/opt/mrpt/lib:/home/thinh/library_build/mongo-cxx-driver/build/install/lib:/opt/mrpt/lib:/home/thinh/library_build/mongo-cxx-driver/build/install/lib'
export PATH='/opt/ros/noetic/bin:/home/thinh/nexus_4wd_mecanum_simulator/devel_isolated/cartographer/bin:/home/thinh/.local/bin:/home/thinh/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/thinh/Desktop/flutter/flutter/bin:/home/thinh/.vscode/extensions/ms-python.debugpy-2025.4.1-linux-x64/bundled/scripts/noConfigScripts:/home/thinh/Desktop/flutter/flutter/bin'
export ROS_PACKAGE_PATH="/home/thinh/nexus_4wd_mecanum_simulator/src/std_stamped_msgs:$ROS_PACKAGE_PATH"