set(_CATKIN_CURRENT_PACKAGE "neo_local_planner")
set(neo_local_planner_VERSION "1.0.1")
set(neo_local_planner_MAINTAINER "Neobotix GmbH <ros@neobotix.de>, Max Wittal <wittal@neobotix.de>")
set(neo_local_planner_PACKAGE_FORMAT "1")
set(neo_local_planner_BUILD_DEPENDS "base_local_planner" "cmake_modules" "costmap_2d" "dynamic_reconfigure" "nav_core" "nav_msgs" "pluginlib" "roscpp" "tf2_ros" "tf2_sensor_msgs" "tf2_geometry_msgs")
set(neo_local_planner_BUILD_EXPORT_DEPENDS "base_local_planner" "costmap_2d" "dynamic_reconfigure" "nav_core" "nav_msgs" "pluginlib" "roscpp" "tf2_ros" "tf2_sensor_msgs" "tf2_geometry_msgs")
set(neo_local_planner_BUILDTOOL_DEPENDS "catkin")
set(neo_local_planner_BUILDTOOL_EXPORT_DEPENDS )
set(neo_local_planner_EXEC_DEPENDS "base_local_planner" "costmap_2d" "dynamic_reconfigure" "nav_core" "nav_msgs" "pluginlib" "roscpp" "tf2_ros" "tf2_sensor_msgs" "tf2_geometry_msgs")
set(neo_local_planner_RUN_DEPENDS "base_local_planner" "costmap_2d" "dynamic_reconfigure" "nav_core" "nav_msgs" "pluginlib" "roscpp" "tf2_ros" "tf2_sensor_msgs" "tf2_geometry_msgs")
set(neo_local_planner_TEST_DEPENDS )
set(neo_local_planner_DOC_DEPENDS )
set(neo_local_planner_URL_WEBSITE "http://wiki.ros.org/base_local_planner")
set(neo_local_planner_URL_BUGTRACKER "")
set(neo_local_planner_URL_REPOSITORY "")
set(neo_local_planner_DEPRECATED "")