// Generated by gencpp from file std_stamped_msgs/ColorRGBAStamped.msg
// DO NOT EDIT!


#ifndef STD_STAMPED_MSGS_MESSAGE_COLORRGBASTAMPED_H
#define STD_STAMPED_MSGS_MESSAGE_COLORRGBASTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace std_stamped_msgs
{
template <class ContainerAllocator>
struct ColorRGBAStamped_
{
  typedef ColorRGBAStamped_<ContainerAllocator> Type;

  ColorRGBAStamped_()
    : stamp()
    , r(0.0)
    , g(0.0)
    , b(0.0)
    , a(0.0)  {
    }
  ColorRGBAStamped_(const ContainerAllocator& _alloc)
    : stamp()
    , r(0.0)
    , g(0.0)
    , b(0.0)
    , a(0.0)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef float _r_type;
  _r_type r;

   typedef float _g_type;
  _g_type g;

   typedef float _b_type;
  _b_type b;

   typedef float _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::std_stamped_msgs::ColorRGBAStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::std_stamped_msgs::ColorRGBAStamped_<ContainerAllocator> const> ConstPtr;

}; // struct ColorRGBAStamped_

typedef ::std_stamped_msgs::ColorRGBAStamped_<std::allocator<void> > ColorRGBAStamped;

typedef boost::shared_ptr< ::std_stamped_msgs::ColorRGBAStamped > ColorRGBAStampedPtr;
typedef boost::shared_ptr< ::std_stamped_msgs::ColorRGBAStamped const> ColorRGBAStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::std_stamped_msgs::ColorRGBAStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::std_stamped_msgs::ColorRGBAStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::std_stamped_msgs::ColorRGBAStamped_<ContainerAllocator1> & lhs, const ::std_stamped_msgs::ColorRGBAStamped_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.r == rhs.r &&
    lhs.g == rhs.g &&
    lhs.b == rhs.b &&
    lhs.a == rhs.a;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::std_stamped_msgs::ColorRGBAStamped_<ContainerAllocator1> & lhs, const ::std_stamped_msgs::ColorRGBAStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace std_stamped_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::std_stamped_msgs::ColorRGBAStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::std_stamped_msgs::ColorRGBAStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::std_stamped_msgs::ColorRGBAStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::std_stamped_msgs::ColorRGBAStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::std_stamped_msgs::ColorRGBAStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::std_stamped_msgs::ColorRGBAStamped_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::std_stamped_msgs::ColorRGBAStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "77543cf1c81098c248475a15489ec55d";
  }

  static const char* value(const ::std_stamped_msgs::ColorRGBAStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x77543cf1c81098c2ULL;
  static const uint64_t static_value2 = 0x48475a15489ec55dULL;
};

template<class ContainerAllocator>
struct DataType< ::std_stamped_msgs::ColorRGBAStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_stamped_msgs/ColorRGBAStamped";
  }

  static const char* value(const ::std_stamped_msgs::ColorRGBAStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::std_stamped_msgs::ColorRGBAStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"float32 r\n"
"float32 g\n"
"float32 b\n"
"float32 a\n"
;
  }

  static const char* value(const ::std_stamped_msgs::ColorRGBAStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::std_stamped_msgs::ColorRGBAStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.r);
      stream.next(m.g);
      stream.next(m.b);
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ColorRGBAStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::std_stamped_msgs::ColorRGBAStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::std_stamped_msgs::ColorRGBAStamped_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "r: ";
    Printer<float>::stream(s, indent + "  ", v.r);
    s << indent << "g: ";
    Printer<float>::stream(s, indent + "  ", v.g);
    s << indent << "b: ";
    Printer<float>::stream(s, indent + "  ", v.b);
    s << indent << "a: ";
    Printer<float>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STD_STAMPED_MSGS_MESSAGE_COLORRGBASTAMPED_H
