// Generated by gencpp from file std_stamped_msgs/StringService.msg
// DO NOT EDIT!


#ifndef STD_STAMPED_MSGS_MESSAGE_STRINGSERVICE_H
#define STD_STAMPED_MSGS_MESSAGE_STRINGSERVICE_H

#include <ros/service_traits.h>


#include <std_stamped_msgs/StringServiceRequest.h>
#include <std_stamped_msgs/StringServiceResponse.h>


namespace std_stamped_msgs
{

struct StringService
{

typedef StringServiceRequest Request;
typedef StringServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StringService
} // namespace std_stamped_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::std_stamped_msgs::StringService > {
  static const char* value()
  {
    return "68e8d6dbd10fbe88400fb3bae3c6f122";
  }

  static const char* value(const ::std_stamped_msgs::StringService&) { return value(); }
};

template<>
struct DataType< ::std_stamped_msgs::StringService > {
  static const char* value()
  {
    return "std_stamped_msgs/StringService";
  }

  static const char* value(const ::std_stamped_msgs::StringService&) { return value(); }
};


// service_traits::MD5Sum< ::std_stamped_msgs::StringServiceRequest> should match
// service_traits::MD5Sum< ::std_stamped_msgs::StringService >
template<>
struct MD5Sum< ::std_stamped_msgs::StringServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::std_stamped_msgs::StringService >::value();
  }
  static const char* value(const ::std_stamped_msgs::StringServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_stamped_msgs::StringServiceRequest> should match
// service_traits::DataType< ::std_stamped_msgs::StringService >
template<>
struct DataType< ::std_stamped_msgs::StringServiceRequest>
{
  static const char* value()
  {
    return DataType< ::std_stamped_msgs::StringService >::value();
  }
  static const char* value(const ::std_stamped_msgs::StringServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::std_stamped_msgs::StringServiceResponse> should match
// service_traits::MD5Sum< ::std_stamped_msgs::StringService >
template<>
struct MD5Sum< ::std_stamped_msgs::StringServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::std_stamped_msgs::StringService >::value();
  }
  static const char* value(const ::std_stamped_msgs::StringServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::std_stamped_msgs::StringServiceResponse> should match
// service_traits::DataType< ::std_stamped_msgs::StringService >
template<>
struct DataType< ::std_stamped_msgs::StringServiceResponse>
{
  static const char* value()
  {
    return DataType< ::std_stamped_msgs::StringService >::value();
  }
  static const char* value(const ::std_stamped_msgs::StringServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STD_STAMPED_MSGS_MESSAGE_STRINGSERVICE_H
