// Generated by gencpp from file std_stamped_msgs/StringServiceResponse.msg
// DO NOT EDIT!


#ifndef STD_STAMPED_MSGS_MESSAGE_STRINGSERVICERESPONSE_H
#define STD_STAMPED_MSGS_MESSAGE_STRINGSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace std_stamped_msgs
{
template <class ContainerAllocator>
struct StringServiceResponse_
{
  typedef StringServiceResponse_<ContainerAllocator> Type;

  StringServiceResponse_()
    : respond()  {
    }
  StringServiceResponse_(const ContainerAllocator& _alloc)
    : respond(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _respond_type;
  _respond_type respond;





  typedef boost::shared_ptr< ::std_stamped_msgs::StringServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::std_stamped_msgs::StringServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StringServiceResponse_

typedef ::std_stamped_msgs::StringServiceResponse_<std::allocator<void> > StringServiceResponse;

typedef boost::shared_ptr< ::std_stamped_msgs::StringServiceResponse > StringServiceResponsePtr;
typedef boost::shared_ptr< ::std_stamped_msgs::StringServiceResponse const> StringServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::std_stamped_msgs::StringServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::std_stamped_msgs::StringServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::std_stamped_msgs::StringServiceResponse_<ContainerAllocator1> & lhs, const ::std_stamped_msgs::StringServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.respond == rhs.respond;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::std_stamped_msgs::StringServiceResponse_<ContainerAllocator1> & lhs, const ::std_stamped_msgs::StringServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace std_stamped_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::std_stamped_msgs::StringServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::std_stamped_msgs::StringServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::std_stamped_msgs::StringServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::std_stamped_msgs::StringServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::std_stamped_msgs::StringServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::std_stamped_msgs::StringServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::std_stamped_msgs::StringServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fd16295e9691f9b17f9af4d745cb5798";
  }

  static const char* value(const ::std_stamped_msgs::StringServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfd16295e9691f9b1ULL;
  static const uint64_t static_value2 = 0x7f9af4d745cb5798ULL;
};

template<class ContainerAllocator>
struct DataType< ::std_stamped_msgs::StringServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_stamped_msgs/StringServiceResponse";
  }

  static const char* value(const ::std_stamped_msgs::StringServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::std_stamped_msgs::StringServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string respond\n"
;
  }

  static const char* value(const ::std_stamped_msgs::StringServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::std_stamped_msgs::StringServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.respond);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StringServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::std_stamped_msgs::StringServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::std_stamped_msgs::StringServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "respond: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.respond);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STD_STAMPED_MSGS_MESSAGE_STRINGSERVICERESPONSE_H
