// Generated by gencpp from file scan_safety/SafetyEnable.msg
// DO NOT EDIT!


#ifndef SCAN_SAFETY_MESSAGE_SAFETYENABLE_H
#define SCAN_SAFETY_MESSAGE_SAFETYENABLE_H

#include <ros/service_traits.h>


#include <scan_safety/SafetyEnableRequest.h>
#include <scan_safety/SafetyEnableResponse.h>


namespace scan_safety
{

struct SafetyEnable
{

typedef SafetyEnableRequest Request;
typedef SafetyEnableResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SafetyEnable
} // namespace scan_safety


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::scan_safety::SafetyEnable > {
  static const char* value()
  {
    return "ae7af90fe0b005a2c2be5fe5227bcaa2";
  }

  static const char* value(const ::scan_safety::SafetyEnable&) { return value(); }
};

template<>
struct DataType< ::scan_safety::SafetyEnable > {
  static const char* value()
  {
    return "scan_safety/SafetyEnable";
  }

  static const char* value(const ::scan_safety::SafetyEnable&) { return value(); }
};


// service_traits::MD5Sum< ::scan_safety::SafetyEnableRequest> should match
// service_traits::MD5Sum< ::scan_safety::SafetyEnable >
template<>
struct MD5Sum< ::scan_safety::SafetyEnableRequest>
{
  static const char* value()
  {
    return MD5Sum< ::scan_safety::SafetyEnable >::value();
  }
  static const char* value(const ::scan_safety::SafetyEnableRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::scan_safety::SafetyEnableRequest> should match
// service_traits::DataType< ::scan_safety::SafetyEnable >
template<>
struct DataType< ::scan_safety::SafetyEnableRequest>
{
  static const char* value()
  {
    return DataType< ::scan_safety::SafetyEnable >::value();
  }
  static const char* value(const ::scan_safety::SafetyEnableRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::scan_safety::SafetyEnableResponse> should match
// service_traits::MD5Sum< ::scan_safety::SafetyEnable >
template<>
struct MD5Sum< ::scan_safety::SafetyEnableResponse>
{
  static const char* value()
  {
    return MD5Sum< ::scan_safety::SafetyEnable >::value();
  }
  static const char* value(const ::scan_safety::SafetyEnableResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::scan_safety::SafetyEnableResponse> should match
// service_traits::DataType< ::scan_safety::SafetyEnable >
template<>
struct DataType< ::scan_safety::SafetyEnableResponse>
{
  static const char* value()
  {
    return DataType< ::scan_safety::SafetyEnable >::value();
  }
  static const char* value(const ::scan_safety::SafetyEnableResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCAN_SAFETY_MESSAGE_SAFETYENABLE_H
