// Generated by gencpp from file scan_safety/SafetyEnableResponse.msg
// DO NOT EDIT!


#ifndef SCAN_SAFETY_MESSAGE_SAFETYENABLERESPONSE_H
#define SCAN_SAFETY_MESSAGE_SAFETYENABLERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scan_safety
{
template <class ContainerAllocator>
struct SafetyEnableResponse_
{
  typedef SafetyEnableResponse_<ContainerAllocator> Type;

  SafetyEnableResponse_()
    : success(false)  {
    }
  SafetyEnableResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::scan_safety::SafetyEnableResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scan_safety::SafetyEnableResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SafetyEnableResponse_

typedef ::scan_safety::SafetyEnableResponse_<std::allocator<void> > SafetyEnableResponse;

typedef boost::shared_ptr< ::scan_safety::SafetyEnableResponse > SafetyEnableResponsePtr;
typedef boost::shared_ptr< ::scan_safety::SafetyEnableResponse const> SafetyEnableResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scan_safety::SafetyEnableResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scan_safety::SafetyEnableResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scan_safety::SafetyEnableResponse_<ContainerAllocator1> & lhs, const ::scan_safety::SafetyEnableResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scan_safety::SafetyEnableResponse_<ContainerAllocator1> & lhs, const ::scan_safety::SafetyEnableResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scan_safety

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::scan_safety::SafetyEnableResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scan_safety::SafetyEnableResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scan_safety::SafetyEnableResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scan_safety::SafetyEnableResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scan_safety::SafetyEnableResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scan_safety::SafetyEnableResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scan_safety::SafetyEnableResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::scan_safety::SafetyEnableResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::scan_safety::SafetyEnableResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scan_safety/SafetyEnableResponse";
  }

  static const char* value(const ::scan_safety::SafetyEnableResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scan_safety::SafetyEnableResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success               # Indicate if the request was successful or not\n"
;
  }

  static const char* value(const ::scan_safety::SafetyEnableResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scan_safety::SafetyEnableResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SafetyEnableResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scan_safety::SafetyEnableResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scan_safety::SafetyEnableResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCAN_SAFETY_MESSAGE_SAFETYENABLERESPONSE_H
