// Generated by gencpp from file scan_safety/SafetyControlRequest.msg
// DO NOT EDIT!


#ifndef SCAN_SAFETY_MESSAGE_SAFETYCONTROLREQUEST_H
#define SCAN_SAFETY_MESSAGE_SAFETYCONTROLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scan_safety
{
template <class ContainerAllocator>
struct SafetyControlRequest_
{
  typedef SafetyControlRequest_<ContainerAllocator> Type;

  SafetyControlRequest_()
    : job(0)  {
    }
  SafetyControlRequest_(const ContainerAllocator& _alloc)
    : job(0)  {
  (void)_alloc;
    }



   typedef int8_t _job_type;
  _job_type job;





  typedef boost::shared_ptr< ::scan_safety::SafetyControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scan_safety::SafetyControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SafetyControlRequest_

typedef ::scan_safety::SafetyControlRequest_<std::allocator<void> > SafetyControlRequest;

typedef boost::shared_ptr< ::scan_safety::SafetyControlRequest > SafetyControlRequestPtr;
typedef boost::shared_ptr< ::scan_safety::SafetyControlRequest const> SafetyControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scan_safety::SafetyControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scan_safety::SafetyControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scan_safety::SafetyControlRequest_<ContainerAllocator1> & lhs, const ::scan_safety::SafetyControlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.job == rhs.job;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scan_safety::SafetyControlRequest_<ContainerAllocator1> & lhs, const ::scan_safety::SafetyControlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scan_safety

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::scan_safety::SafetyControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scan_safety::SafetyControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scan_safety::SafetyControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scan_safety::SafetyControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scan_safety::SafetyControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scan_safety::SafetyControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scan_safety::SafetyControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4d654414b2b49d7a8fdaa9b3e1b14967";
  }

  static const char* value(const ::scan_safety::SafetyControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4d654414b2b49d7aULL;
  static const uint64_t static_value2 = 0x8fdaa9b3e1b14967ULL;
};

template<class ContainerAllocator>
struct DataType< ::scan_safety::SafetyControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scan_safety/SafetyControlRequest";
  }

  static const char* value(const ::scan_safety::SafetyControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scan_safety::SafetyControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 job\n"
;
  }

  static const char* value(const ::scan_safety::SafetyControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scan_safety::SafetyControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.job);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SafetyControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scan_safety::SafetyControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scan_safety::SafetyControlRequest_<ContainerAllocator>& v)
  {
    s << indent << "job: ";
    Printer<int8_t>::stream(s, indent + "  ", v.job);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCAN_SAFETY_MESSAGE_SAFETYCONTROLREQUEST_H
