// Generated by gencpp from file scan_safety/SafetyControlResponse.msg
// DO NOT EDIT!


#ifndef SCAN_SAFETY_MESSAGE_SAFETYCONTROLRESPONSE_H
#define SCAN_SAFETY_MESSAGE_SAFETYCONTROLRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scan_safety
{
template <class ContainerAllocator>
struct SafetyControlResponse_
{
  typedef SafetyControlResponse_<ContainerAllocator> Type;

  SafetyControlResponse_()
    : result(false)  {
    }
  SafetyControlResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::scan_safety::SafetyControlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scan_safety::SafetyControlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SafetyControlResponse_

typedef ::scan_safety::SafetyControlResponse_<std::allocator<void> > SafetyControlResponse;

typedef boost::shared_ptr< ::scan_safety::SafetyControlResponse > SafetyControlResponsePtr;
typedef boost::shared_ptr< ::scan_safety::SafetyControlResponse const> SafetyControlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scan_safety::SafetyControlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scan_safety::SafetyControlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scan_safety::SafetyControlResponse_<ContainerAllocator1> & lhs, const ::scan_safety::SafetyControlResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scan_safety::SafetyControlResponse_<ContainerAllocator1> & lhs, const ::scan_safety::SafetyControlResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scan_safety

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::scan_safety::SafetyControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scan_safety::SafetyControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scan_safety::SafetyControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scan_safety::SafetyControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scan_safety::SafetyControlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scan_safety::SafetyControlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scan_safety::SafetyControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::scan_safety::SafetyControlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::scan_safety::SafetyControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scan_safety/SafetyControlResponse";
  }

  static const char* value(const ::scan_safety::SafetyControlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scan_safety::SafetyControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n"
;
  }

  static const char* value(const ::scan_safety::SafetyControlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scan_safety::SafetyControlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SafetyControlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scan_safety::SafetyControlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scan_safety::SafetyControlResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCAN_SAFETY_MESSAGE_SAFETYCONTROLRESPONSE_H
