// Generated by gencpp from file scan_safety/SafetyControl.msg
// DO NOT EDIT!


#ifndef SCAN_SAFETY_MESSAGE_SAFETYCONTROL_H
#define SCAN_SAFETY_MESSAGE_SAFETYCONTROL_H

#include <ros/service_traits.h>


#include <scan_safety/SafetyControlRequest.h>
#include <scan_safety/SafetyControlResponse.h>


namespace scan_safety
{

struct SafetyControl
{

typedef SafetyControlRequest Request;
typedef SafetyControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SafetyControl
} // namespace scan_safety


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::scan_safety::SafetyControl > {
  static const char* value()
  {
    return "bc1260ea4239d795414826aa59e7fb9a";
  }

  static const char* value(const ::scan_safety::SafetyControl&) { return value(); }
};

template<>
struct DataType< ::scan_safety::SafetyControl > {
  static const char* value()
  {
    return "scan_safety/SafetyControl";
  }

  static const char* value(const ::scan_safety::SafetyControl&) { return value(); }
};


// service_traits::MD5Sum< ::scan_safety::SafetyControlRequest> should match
// service_traits::MD5Sum< ::scan_safety::SafetyControl >
template<>
struct MD5Sum< ::scan_safety::SafetyControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::scan_safety::SafetyControl >::value();
  }
  static const char* value(const ::scan_safety::SafetyControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::scan_safety::SafetyControlRequest> should match
// service_traits::DataType< ::scan_safety::SafetyControl >
template<>
struct DataType< ::scan_safety::SafetyControlRequest>
{
  static const char* value()
  {
    return DataType< ::scan_safety::SafetyControl >::value();
  }
  static const char* value(const ::scan_safety::SafetyControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::scan_safety::SafetyControlResponse> should match
// service_traits::MD5Sum< ::scan_safety::SafetyControl >
template<>
struct MD5Sum< ::scan_safety::SafetyControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::scan_safety::SafetyControl >::value();
  }
  static const char* value(const ::scan_safety::SafetyControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::scan_safety::SafetyControlResponse> should match
// service_traits::DataType< ::scan_safety::SafetyControl >
template<>
struct DataType< ::scan_safety::SafetyControlResponse>
{
  static const char* value()
  {
    return DataType< ::scan_safety::SafetyControl >::value();
  }
  static const char* value(const ::scan_safety::SafetyControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCAN_SAFETY_MESSAGE_SAFETYCONTROL_H
