// Generated by gencpp from file safety_msgs/SafetyJob.msg
// DO NOT EDIT!


#ifndef SAFETY_MSGS_MESSAGE_SAFETYJOB_H
#define SAFETY_MSGS_MESSAGE_SAFETYJOB_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Polygon.h>
#include <geometry_msgs/Polygon.h>

namespace safety_msgs
{
template <class ContainerAllocator>
struct SafetyJob_
{
  typedef SafetyJob_<ContainerAllocator> Type;

  SafetyJob_()
    : header()
    , footprint()
    , jobs()  {
    }
  SafetyJob_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , footprint(_alloc)
    , jobs(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Polygon_<ContainerAllocator>  _footprint_type;
  _footprint_type footprint;

   typedef std::vector< ::geometry_msgs::Polygon_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Polygon_<ContainerAllocator> >> _jobs_type;
  _jobs_type jobs;





  typedef boost::shared_ptr< ::safety_msgs::SafetyJob_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::safety_msgs::SafetyJob_<ContainerAllocator> const> ConstPtr;

}; // struct SafetyJob_

typedef ::safety_msgs::SafetyJob_<std::allocator<void> > SafetyJob;

typedef boost::shared_ptr< ::safety_msgs::SafetyJob > SafetyJobPtr;
typedef boost::shared_ptr< ::safety_msgs::SafetyJob const> SafetyJobConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::safety_msgs::SafetyJob_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::safety_msgs::SafetyJob_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::safety_msgs::SafetyJob_<ContainerAllocator1> & lhs, const ::safety_msgs::SafetyJob_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.footprint == rhs.footprint &&
    lhs.jobs == rhs.jobs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::safety_msgs::SafetyJob_<ContainerAllocator1> & lhs, const ::safety_msgs::SafetyJob_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace safety_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::safety_msgs::SafetyJob_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::safety_msgs::SafetyJob_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::safety_msgs::SafetyJob_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::safety_msgs::SafetyJob_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::safety_msgs::SafetyJob_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::safety_msgs::SafetyJob_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::safety_msgs::SafetyJob_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f6ba680ca90f32e0964e7c70a10d72b5";
  }

  static const char* value(const ::safety_msgs::SafetyJob_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf6ba680ca90f32e0ULL;
  static const uint64_t static_value2 = 0x964e7c70a10d72b5ULL;
};

template<class ContainerAllocator>
struct DataType< ::safety_msgs::SafetyJob_<ContainerAllocator> >
{
  static const char* value()
  {
    return "safety_msgs/SafetyJob";
  }

  static const char* value(const ::safety_msgs::SafetyJob_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::safety_msgs::SafetyJob_<ContainerAllocator> >
{
  static const char* value()
  {
    return " Header header\n"
"\n"
" geometry_msgs/Polygon footprint  # polygon of footprint\n"
" geometry_msgs/Polygon[] jobs     # polygon of jobs\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Polygon\n"
"#A specification of a polygon where the first and last points are assumed to be connected\n"
"Point32[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::safety_msgs::SafetyJob_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::safety_msgs::SafetyJob_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.footprint);
      stream.next(m.jobs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SafetyJob_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::safety_msgs::SafetyJob_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::safety_msgs::SafetyJob_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "footprint: ";
    s << std::endl;
    Printer< ::geometry_msgs::Polygon_<ContainerAllocator> >::stream(s, indent + "  ", v.footprint);
    s << indent << "jobs[]" << std::endl;
    for (size_t i = 0; i < v.jobs.size(); ++i)
    {
      s << indent << "  jobs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Polygon_<ContainerAllocator> >::stream(s, indent + "    ", v.jobs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAFETY_MSGS_MESSAGE_SAFETYJOB_H
