// Generated by gencpp from file safety_msgs/SafetyStatus.msg
// DO NOT EDIT!


#ifndef SAFETY_MSGS_MESSAGE_SAFETYSTATUS_H
#define SAFETY_MSGS_MESSAGE_SAFETYSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace safety_msgs
{
template <class ContainerAllocator>
struct SafetyStatus_
{
  typedef SafetyStatus_<ContainerAllocator> Type;

  SafetyStatus_()
    : header()
    , id(0)
    , name()
    , job(0)
    , fields()  {
    }
  SafetyStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , name(_alloc)
    , job(0)
    , fields(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef int8_t _job_type;
  _job_type job;

   typedef std::vector<int8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int8_t>> _fields_type;
  _fields_type fields;





  typedef boost::shared_ptr< ::safety_msgs::SafetyStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::safety_msgs::SafetyStatus_<ContainerAllocator> const> ConstPtr;

}; // struct SafetyStatus_

typedef ::safety_msgs::SafetyStatus_<std::allocator<void> > SafetyStatus;

typedef boost::shared_ptr< ::safety_msgs::SafetyStatus > SafetyStatusPtr;
typedef boost::shared_ptr< ::safety_msgs::SafetyStatus const> SafetyStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::safety_msgs::SafetyStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::safety_msgs::SafetyStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::safety_msgs::SafetyStatus_<ContainerAllocator1> & lhs, const ::safety_msgs::SafetyStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.id == rhs.id &&
    lhs.name == rhs.name &&
    lhs.job == rhs.job &&
    lhs.fields == rhs.fields;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::safety_msgs::SafetyStatus_<ContainerAllocator1> & lhs, const ::safety_msgs::SafetyStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace safety_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::safety_msgs::SafetyStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::safety_msgs::SafetyStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::safety_msgs::SafetyStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::safety_msgs::SafetyStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::safety_msgs::SafetyStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::safety_msgs::SafetyStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::safety_msgs::SafetyStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3813fc5ff23effa131d96d27a6d41099";
  }

  static const char* value(const ::safety_msgs::SafetyStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3813fc5ff23effa1ULL;
  static const uint64_t static_value2 = 0x31d96d27a6d41099ULL;
};

template<class ContainerAllocator>
struct DataType< ::safety_msgs::SafetyStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "safety_msgs/SafetyStatus";
  }

  static const char* value(const ::safety_msgs::SafetyStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::safety_msgs::SafetyStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int8 id\n"
"string name\n"
"int8 job           # current job\n"
"int8[] fields      # fields status\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::safety_msgs::SafetyStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::safety_msgs::SafetyStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.name);
      stream.next(m.job);
      stream.next(m.fields);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SafetyStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::safety_msgs::SafetyStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::safety_msgs::SafetyStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.id);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "job: ";
    Printer<int8_t>::stream(s, indent + "  ", v.job);
    s << indent << "fields[]" << std::endl;
    for (size_t i = 0; i < v.fields.size(); ++i)
    {
      s << indent << "  fields[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.fields[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAFETY_MSGS_MESSAGE_SAFETYSTATUS_H
